#!/bin/sh
SCRIPT_DIR=$(cd $(dirname $0); pwd)
if [ "$1" = "" ] ; then
	echo "No arguments"
	exit 1
fi

if [ -e "$1" ] ; then
	echo "File already exists"
	exit 1
fi

cat $SCRIPT_DIR/ac_template.cpp >> $1
